[DATAR]
DataR_node_name=pkgz
parallel_thread_per_task=10
#send_buffer_size=20480
# 这个单位在PG下为8KB的倍数，因为PG的默认页面大小为8KB。只要不包含toast字段，大多数情况下足够使用。在mysql下为16KB的倍数
# 缓冲区判定满的标志为剩余不到2个页面的大小。即： send_buffer_size*page_size-2*page_size
# 意外情况：toast长度超过2*page_size时，最后一次填充缓冲区可能会溢出。  
# 改成在控制台传递参数，每个任务可调

# buffer=32   max_t 70   63,829s/m
#最大的一个字段长度，默认1K，单位1k，使用者应当对所有字段的长度进行预估，避免出内存越界的风险，可适当大一些

#减速轮次，读取多少行数据之后减速一次。默认100
deceleration_rounds=10000
#迁移速度轮次，读取多少行数据之后进行一次速度统计，默认100000
calculate_speed_rounds=100000
#socket最大连接数，建议设置为cpu核心数
listen_backlog=50
#控制中心IP和端口
control_center_ip=
#control_center_ip=192.168.68.89
control_center_port=
#本机监听地址和端口
DataR_listener_ip=127.0.0.1
#接收缓冲区大小，防止--create 任务中的pump_sql 太长服务器无法接受。
recv_buffer_size=81920
DataR_listener_port=1234

 
