#ifndef _MESSAGE_TYPE_H_
#define _MESSAGE_TYPE_H_

#define TASK_CREATE_OK "NODE_CREFINI_"
#define TASK_CREATE_FAILED "NODE_CREFAIL_"
#define TASK_FINISH "NODE_TASFINI_"

#define TASK_ADJUST_OK "NODE_ADJFINI_"
#define TASK_ADJUST_FAILED "NODE_ADJFAIL_"

#define TASK_DELETE_OK  "NODE_DELFINI_"
#define TASK_DELETE_FAILED "NODE_DELERRO_"

#define DB_CONN_ERROR "NODE_DBCERRO_"

#endif